### ISSUE TITLE
'opera failed to access or upgrade your profile'

### ISSUE THREAD

**Issue by tomsem** [operasoftware/operaprestodriver#34]
I installed Opera 11.52 and am trying to use the Selenium webdriver bindings for Python to launch Opera with the Remote interface (Python bindings don't support Opera directly). Opera starts to launch, but gives the above 'Startup error'. It launches normally otherwise. I may try with Java just to see if that goes better. Any suggestions?

**Comment by andreastt** [comment]
I take it you are using Windows?  Your Opera is installed to a directory to which OperaDriver cannot write.  If you use an Opera installed to a writable directory or run your code as Administrator, that should solve it.

The core of the issue is that Opera 11.5x does not support specifying which profile to use during startup, meaning it will (on Windows) write to C:\Program Files\Opera.autotestprofile (or something similar).  Specifying this is supported in 11.60 Beta and in Opera Next 12.x.

You can get Opera 12 from here: http://www.opera.com/browser/next/

With Opera 12 you should have no issues, as it writes the profile to a writable temporary directory.

See this for more reference: https://github.com/operasoftware/operadriver/issues/8
