### ISSUE TITLE
Extension Support

### ISSUE THREAD

**Issue by farlan** [operasoftware/operaprestodriver#60]
Is there a way to support extensions in OperaDriver? 
I am looking for functionality similar to that of FirefoxDriver.

**Comment by andreastt** [comment]
Do you mean something like this?

```
OperaProfile profile = new OperaProfile();
profile.addExtension(new File("/path/to/extension.oex"));
OperaDriver driver = new OperaDriver(profile);
```

The above is an example of functionality I'd like to add to OperaDriver.

**Comment by farlan** [comment]
Yes, that is the functionality I am looking for (assuming it currently doesn't exist as I could not find anything saying otherwise)

**Comment by andreastt** [comment]
We decided not to support this.

**Comment by Rob--W** [comment]
@andreasbovens What's the rationale for not supporting it? Do you not want to dedicate time to the feature, or are you opposed to the feature?

With a bit of reverse-engineering, I figured out Opera's extension settings format, which allows me to automate the installation of Opera 12 extensions.
I'm about to implement this feature for Opera 12.xx, and was wondering if you would accept a PR which implements automated installation of Opera extensions.

**Comment by andreasbovens** [comment]
@andreastt closed this, not @andreasbovens, but now that you have me here, I can just as well answer :)

At this point, it doesn't make sense to invest any time in supporting this, as Opera extensions are discontinued. Opera 15 supports Chromium extensions, and that's where we are investing our efforts at the moment.

**Comment by Rob--W** [comment]
@andreasbovens I expect a significant number of users to stick to Opera 12 for a while, similar to how Firefox 3.6 lived around forever when Firefox started a rapid release schedule. I've already implemented automated installation of Safari extensions, so doing the same for Opera 12 would not be too hard.

I've attempted the ChromeDriver with Opera 15 without success. Extensions were installed (probably because of matching command-line arguments), but the automation didn't catch up at all. [I have tweeted ODevRel](https://twitter.com/RobSinje/status/350001125900038145), but didn't get a response. Since you just mentioned that you're working on the Opera 15 version, do you happen to know how to get Selenium WebDriver to work with Opera 15?

**Comment by andreastt** [comment]
I think you're right in your assertions, but feature development for Presto-OperaDriver is not a priority.  I don't think adding extension support to OperaProfile should be particularly hard, so anyone with a bit of spare time on their hands could put in the effort: Patches are always welcome (-:

As for the situation with Opera 15, since it's based on Chromium and Blink it inherits the Remote Debugging Protocol used by the new chromedriver, but we haven't yet had time to bake chromedriver support in to the new Opera.

**Comment by Rob--W** [comment]
@andreastt :point_up:
