### ISSUE TITLE
OperaDriver needs administrator privileges

### ISSUE THREAD

**Issue by shauvik** [operasoftware/operaprestodriver#8]
Hi,

OperaDriver needs administrator privileges on Windows 7. This doesn't seem correct.

Without admin privileges, i get the following error:
http://dl.dropbox.com/u/32626775/bugs/opera_webdriver.png

It would be nice if operadriver could run without admin privileges.

Thanks,
Shauvik

**Comment by Stuk** [comment]
I've updated the [readme](https://github.com/operasoftware/operadriver/blob/master/README.txt) to explain the situation and a couple of solutions (under the Test Profile section).

Ideally we wouldn't need admin privileges, and hopefully this will change in the future.

**Comment by andreastt** [comment]
What are we doing exactly that requires admin privileges?

**Comment by Stuk** [comment]
Writing to the Program Files directory.

**Comment by andreastt** [comment]
It's entirely possible that we want to change this, so that OperaDriver doesn't require you to have administrator privileges, which seems bad for a multiple reasons, when running on Windows 7.

**Comment by shs96c** [comment]
Writing to the temp dir might be a better option.

**Comment by andreastt** [comment]
Opera 11.60 and Opera 12 supports writing to a temporary directory on the system.  You can try them out from here: http://www.opera.com/browser/next/

To use Opera 11.5x with OperaDriver there is currently no other workaround than either installing Opera in a directory writable by your current user, or to run as Administrator.

As I said, this problem will be fixed with the next version of Opera, so my own recommendation is to use Opera Next (12.00) for the time being.
